# Generated by Django 5.1.15 on 2026-09-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-updated_at', '-created_at']},
        ),
    ]
