# Generated by Django 5.1.15 on 2026-08-16 17:27

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity_available", models.IntegerField(default=0)),
                ("quantity_reserved", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_items",
            },
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("stock_received", "Stock Received"),
                            ("manual_adjustment", "Manual Adjustment"),
                            ("order_reserved", "Order Reserved"),
                            ("reservation_released", "Reservation Released"),
                            ("order_fulfilled", "Order Fulfilled"),
                            ("return_received", "Return Received"),
                            ("damaged", "Damaged"),
                        ],
                        max_length=30,
                    ),
                ),
                ("quantity_change", models.IntegerField()),
                ("reference", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_movements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("released", "Released"),
                            ("finalized", "Finalized"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_reservations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_available__gte", 0)),
                name="chk_quantity_available_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_reserved__gte", 0)),
                name="chk_quantity_reserved_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["inventory_item", "movement_type"],
                name="idx_movement_item_type",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryreservation",
            index=models.Index(
                fields=["inventory_item", "status"], name="idx_reservation_item_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="chk_reservation_quantity_positive",
            ),
        ),
    ]
