# Generated by Django 5.1.15 on 2026-10-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cart', '0002_cart_user_alter_cart_session_key_and_more'),
        ('orders', '0002_order_cart_order_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Razorpay order identifier (order_xxxx).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_index=True, help_text='Razorpay payment identifier (pay_xxxx).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, help_text='Razorpay payment verification signature.', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('razorpay_order_id__isnull', False)), fields=('razorpay_order_id',), name='uq_order_razorpay_order_id'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('razorpay_payment_id__isnull', False)), fields=('razorpay_payment_id',), name='uq_order_razorpay_payment_id'),
        ),
    ]
